kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdbench-pv-claim
  labels:
    fio: kdbench
spec:
  storageClassName: << INPUT STORAGECLASS >> # Must change in here 
  # storageClassName: managed-nfs-storage 
  # storageClassName: gp2 
  # storageClassName: default 
  # storageClassName: standard 
  # storageClassName: nks-block-storage
  accessModes:
    - ReadWriteOnce   # (optional) RWO - ReadWriteOnce, ROX - ReadOnlyMany, RWX - ReadWriteMany, RWOP - ReadWriteOncePod
  resources:
    requests:
      storage: 100Gi  # (optional) filestore standard - 1000Gi, filestore premium - 2560Gi 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kdbench
  labels:
    fio: kdbench
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: kdbench
        image: sysnet4admin/kdbench:latest
        imagePullPolicy: Always
        env:
          - name: KDBENCH_MOUNTPOINT
            value: /tmp
          # - name: STORAGECLASS
          #   value: your-storageclass
          # - name: KDBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "1"
        volumeMounts:
        - name: kdbench-pv
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: kdbench-pv
        persistentVolumeClaim:
          claimName: kdbench-pv-claim
  backoffLimit: 4
